// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class College {
    "code": string;
    "name": string;

    /** Creates a new College instance. */
    constructor($$source: Partial<College> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new College instance from a string or object.
     */
    static createFrom($$source: any = {}): College {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new College($$parsedSource as Partial<College>);
    }
}
