// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class College {
    "code": string;
    "name": string;

    /** Creates a new College instance. */
    constructor($$source: Partial<College> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new College instance from a string or object.
     */
    static createFrom($$source: any = {}): College {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new College($$parsedSource as Partial<College>);
    }
}

export class Program {
    "code": string;
    "name": string;
    "college_code": string;
    "college": College;

    /** Creates a new Program instance. */
    constructor($$source: Partial<Program> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("college_code" in $$source)) {
            this["college_code"] = "";
        }
        if (!("college" in $$source)) {
            this["college"] = (new College());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Program instance from a string or object.
     */
    static createFrom($$source: any = {}): Program {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("college" in $$parsedSource) {
            $$parsedSource["college"] = $$createField3_0($$parsedSource["college"]);
        }
        return new Program($$parsedSource as Partial<Program>);
    }
}

export class Student {
    "id": string;
    "first_name": string;
    "last_name": string;
    "year": number;
    "gender": string;
    "program_code": string;
    "program": Program;

    /** Creates a new Student instance. */
    constructor($$source: Partial<Student> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("first_name" in $$source)) {
            this["first_name"] = "";
        }
        if (!("last_name" in $$source)) {
            this["last_name"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("gender" in $$source)) {
            this["gender"] = "";
        }
        if (!("program_code" in $$source)) {
            this["program_code"] = "";
        }
        if (!("program" in $$source)) {
            this["program"] = (new Program());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Student instance from a string or object.
     */
    static createFrom($$source: any = {}): Student {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("program" in $$parsedSource) {
            $$parsedSource["program"] = $$createField6_0($$parsedSource["program"]);
        }
        return new Student($$parsedSource as Partial<Student>);
    }
}

// Private type creation functions
const $$createType0 = College.createFrom;
const $$createType1 = Program.createFrom;
